//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActTransportation
    {
        public long addressID { get; set; }
        public long contractID { get; set; }
        public long transportID { get; set; }
        public string actNumber { get; set; }
        public string CMR { get; set; }
        public Nullable<long> TrailerID { get; set; }
    }
}
