//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid addressID { get; set; }
        public string index { get; set; }
        public string state { get; set; }
        public string region { get; set; }
        public string district { get; set; }
        public string town { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string flat { get; set; }
        public string type { get; set; }
    }
}
