//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery
    {
        public long batteryID { get; set; }
        public string type { get; set; }
        public string factory { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public long transportID { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public string mileageMonth { get; set; }
        public string mileageFromStart { get; set; }
        public string status { get; set; }
        public string endReason { get; set; }
    }
}
