//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public long contractID { get; set; }
        public long PerformerID { get; set; }
        public long CustomerID { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateUntil { get; set; }
        public string Place { get; set; }
    
        public virtual ContractStreak ContractStreak { get; set; }
    }
}
