//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingLicence
    {
        public string licenceNumber { get; set; }
        public long organizationID { get; set; }
        public Nullable<bool> A1 { get; set; }
        public string tableNumber { get; set; }
        public Nullable<bool> A { get; set; }
        public Nullable<bool> B { get; set; }
        public Nullable<bool> C { get; set; }
        public Nullable<bool> D { get; set; }
        public Nullable<bool> BE { get; set; }
        public Nullable<bool> CE { get; set; }
        public Nullable<bool> DE { get; set; }
        public Nullable<bool> I { get; set; }
        public Nullable<bool> F { get; set; }
        public Nullable<System.DateTime> issueDate { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
    }
}
