//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long addressID { get; set; }
        public long organizationID { get; set; }
        public string tableNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ParentName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string IDnumber { get; set; }
        public string PassportSerie { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassportUntil { get; set; }
        public Nullable<System.DateTime> DatePassportFrom { get; set; }
        public string position { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
