//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public long maintenanceID { get; set; }
        public long transportID { get; set; }
        public System.DateTime dateFrom { get; set; }
        public System.DateTime dateUntil { get; set; }
        public long typeCostID { get; set; }
        public Nullable<decimal> cost { get; set; }
    }
}
