//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public string addressID { get; set; }
        public long organizationID { get; set; }
        public string FullTitle { get; set; }
        public string ShortTitle { get; set; }
        public string RegistrationNumber { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string UNP { get; set; }
        public string OKPO { get; set; }
        public string directorID { get; set; }
        public string rs { get; set; }
        public string bankInfo { get; set; }
        public string ks { get; set; }
        public string BIK { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
