//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long RequestNumber { get; set; }
        public long contractID { get; set; }
        public long transportID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Sender { get; set; }
        public string Recipient { get; set; }
        public string Shipment { get; set; }
        public string OffloadingPlace { get; set; }
        public string NumberOfSeats { get; set; }
        public string Packing { get; set; }
        public decimal Cost { get; set; }
        public string SpecialNotes { get; set; }
    }
}
