//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tire
    {
        public long TireID { get; set; }
        public string state { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public string factoryNumber { get; set; }
        public Nullable<double> mileageNorm { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string provider { get; set; }
        public long organizationID { get; set; }
        public Nullable<double> MileageFromStart { get; set; }
    }
}
