//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public long transportID { get; set; }
        public string model { get; set; }
        public string registrationNumber { get; set; }
        public string VIN { get; set; }
        public string transportType { get; set; }
        public string transportCategory { get; set; }
        public Nullable<long> transportMakingYear { get; set; }
        public string ecologyClass { get; set; }
        public Nullable<float> maxWeight { get; set; }
        public Nullable<float> weight { get; set; }
        public string engineType { get; set; }
        public Nullable<float> engineVolume { get; set; }
    }
}
