//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportStateReport
    {
        public long reportID { get; set; }
        public long organizationID { get; set; }
        public Nullable<long> routeID { get; set; }
        public long transportID { get; set; }
        public long tableNumber { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string location { get; set; }
    }
}
