//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCost
    {
        public long typeCostID { get; set; }
        public string typeCostName { get; set; }
        public Nullable<bool> repair { get; set; }
        public Nullable<bool> service { get; set; }
    }
}
